db:
  image: mariadb:10.2
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_DATABASE: neos

web:
  image: ttree/flowapp
  ports:
    - '8000:8000'
  links:
    - db:db
    - redis:redis
  volumes:
    - .:/var/www
    - .:/data
    - ./Caddyfile:/etc/Caddyfile
  environment:
    VIRTUAL_HOST: localhost
    VIRTUAL_PORT: 8000
redis:
    image: redis:3.0
