Neos:
  ContentRepository:
    contentDimensions:
      language:
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          all: null
          de:
            label: Deutsch
            values:
              - de
            uriSegment: de
